
user root;

worker_processes  4;

events {
    worker_connections  65535;
}


http {
    include       mime.types;

    underscores_in_headers on;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /home/server/nginx/logs/access.log  main;

    client_header_buffer_size 32k;
    client_max_body_size 200m;
    sendfile        on;
    keepalive_timeout  180;

	server {
		listen 8081;
        
		
		location ~/fins-oa-console/ {
			root /home/server/html;
			index index.html;
			try_files $uri $uri/ /fins-oa-console/index.html;
		}

		location / {
			root /home/server/html;
			index index.html;
			try_files $uri $uri/ /index.html;
		} 


        location /tuling/ibocr/ {
            proxy_pass https://cloud.iflysec.com/tuling/ibocr/;
        }

		
	location /fins-oa-server/ {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Headers X-Requested-With;
            add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	   proxy_pass http://127.0.0.1:48080/fins-oa-server/;
        }
	
    }

}
